#save point

diff --git a/tools/cli/commands/content-type b/tools/cli/commands/content-type
--- a/tools/cli/commands/content-type
+++ b/tools/cli/commands/content-type
@@ -6,10 +6,12 @@ help_push_content_type() {
   echo "
 Command: content-type
 
+This command takes a json file describing the CT that will be pushed/updated
+
 Usage:
-  ./dot-cli --content-type -f ~/code/etc/content-type.json
+  ./dot-cli --content-type ~/code/etc/content-type.json
   or
-  ./dot-cli --content-type --file ~/code/etc/content-type.json
+  ./dot-cli --content-type ~/code/etc/content-type.json
    "
   exit 1
 }
@@ -35,12 +37,34 @@ code=$(curl -s -o /dev/null --head -w "%{http_code}" --header "Authorization: Be
 
 if [[ $code = 404 ]]
 then
-   echo "Content-type does not exists on remote site add will be attempted."
+   echo "Content-type does not exists on remote site. Add will be attempted."
 
    response=$(curl -s "${DOTCMS_BASE_URL}/api/v1/contenttype"  --header "Authorization: Bearer ${JSON_WEB_TOKEN}" --header 'Content-Type: application/json' --data-raw  "$jsonContentType"  --compressed)
+   echo "$response"
+   identifier=$(jq -r '.entity[].id' <<< "$response")
+   echo "New content-type identifier :: $identifier"
+
+   printf ${identifier} >> $publishMeFile
 
   else
-  echo "A content type named $contentTypeVar already exists."
+  echo "A content type named $contentTypeVar already exists. Update will be attempted."
+
+  response=$(curl -s -X PUT "${DOTCMS_BASE_URL}/api/v1/contenttype/id/${contentTypeVar}"  --header "Authorization: Bearer ${JSON_WEB_TOKEN}" --header 'Content-Type: application/json' --data-raw  "$jsonContentType"  --compressed)
+  echo "$response"
+
+  identifier=$(jq -r ' try .entity[].id' <<< "$response")
+
+  if [[ -z ${identifier} ]];
+  then
+    echo "Unable to get identifier from response. Please check if there were any error messages."
+    exit 1
+  fi
+
+  echo " Updated content-type identifier :: $identifier"
+
+  printf ${identifier} >> $publishMeFile
+
+
 fi
 
 
diff --git a/tools/cli/commands/site b/tools/cli/commands/site
--- a/tools/cli/commands/site
+++ b/tools/cli/commands/site
@@ -6,6 +6,8 @@ help_push_site() {
   echo "
 Command: site
 
+This command takes a json file describing the Site that will be pushed/updated
+
 Usage:
   ./dot-cli --site ~/code/etc/site.json
   or
@@ -44,6 +46,18 @@ then
    response=$(curl -s -X POST "${DOTCMS_BASE_URL}/api/v1/site" --header "Authorization: Bearer ${JSON_WEB_TOKEN}" --header 'Content-Type: application/json' --data-raw  "$jsonSite"  --compressed)
 
    echo "$response"
+
+   identifier=$(jq -r 'try .entity.identifier' <<< "$response")
+
+   if [[ -z ${identifier} ]];
+   then
+    echo "Unable to get identifier from response. Please check if there were any error messages."
+    exit 1
+   fi
+
+   echo " Updated content-type identifier :: $identifier"
+
+   printf ${identifier} >> $publishMeFile
 
   else
    echo "A site named $siteName already exists."
