#28259 setting node on the PATH. +1

diff --git a/core-web/.husky/pre-commit b/core-web/.husky/pre-commit
--- a/core-web/.husky/pre-commit
+++ b/core-web/.husky/pre-commit
@@ -16,6 +16,28 @@ NC='\033[0m' # No Color
     exit 1
 }
 
+# Load nvm and use the version specified in .nvmrc
+load_nvm_and_use_node() {
+    export NVM_DIR="$HOME/.nvm"
+    if [ -s "$NVM_DIR/nvm.sh" ]; then
+        . "$NVM_DIR/nvm.sh"  # This loads nvm
+        echo "nvm loaded."
+
+        if [ -f ".nvmrc" ]; then
+            nvm use || {
+                echo "Failed to switch to Node version specified in .nvmrc"
+                exit 1
+            }
+            echo "Using Node version from .nvmrc"
+        else
+            echo "No .nvmrc file found. Using default Node version."
+        fi
+    else
+        echo "nvm is not installed or could not be found."
+        exit 1
+    fi
+}
+
 check_sdk_client_affected() {
     local YARN_EXEC="${root_dir}/installs/node/yarn/dist/bin/yarn"
     local affected_projects=$(npx nx show projects --affected)
@@ -200,6 +222,9 @@ fi
 core_web_dir="${root_dir}/core-web"
 cd "${core_web_dir}" || exit 1
 
+# Load nvm and use the node version specified in .nvmrc
+load_nvm_and_use_node
+
 staged_files=$(git diff --cached --name-only)
 modified_files=$(git diff --name-only)
 
@@ -268,10 +293,13 @@ sdk_files_staged=$(echo "$staged_files" | grep -E '^core-web/libs/sdk/' || true)
 if [ -n "$sdk_files_staged" ]; then
     echo "Changes detected in core-web/libs/sdk. Running bump-sdk-versions.js"
 
-    nvm use
-    # NODE_EXEC="${root_dir}/installs/node/node"
+    # use nvm
+    # local NODE_EXEC="${root_dir}/installs/node/node"
+    # ${NODE_EXEC} --version
 
-    if ! node "${root_dir}/core-web/bump-sdk-versions.js"; then
+    NODE_EXEC="node"
+
+    if ! $NODE_EXEC "${root_dir}/core-web/bump-sdk-versions.js"; then
         echo "Failed to update versions"
         has_errors=true
     else
