#28259 changing the way of verifying sdk updates.

diff --git a/core-web/.husky/pre-commit b/core-web/.husky/pre-commit
--- a/core-web/.husky/pre-commit
+++ b/core-web/.husky/pre-commit
@@ -21,26 +21,12 @@ check_sdk_client_affected() {
     local affected_projects=$(npx nx show projects --affected)
     echo "Affected projects: $affected_projects"
 
-    # Check if sdk-client, sdk-angular, or sdk-react are affected
-    if echo "$affected_projects" | grep -qE "sdk-client|sdk-angular|sdk-react"; then
-        echo "Running update-versions.js script"
-        if ! node "${root_dir}/core-web/bump-sdk-versions.js"; then
-            echo "Failed to update versions"
+    # Build sdk-client if affected
+    if echo "$affected_projects" | grep -q "sdk-client"; then
+        echo "Building sdk-client"
+        if ! $YARN_EXEC nx run sdk-client:build:js; then
+            echo "Failed to build sdk-client"
             has_errors=true
-        else
-            # Add all modified package.json files to staging
-            git add "${root_dir}/core-web/libs/sdk/"
-            git add "${root_dir}/examples/"
-            echo "Staged updated package.json files for SDKs and examples"
-        fi
-
-        # Build sdk-client if affected
-        if echo "$affected_projects" | grep -q "sdk-client"; then
-            echo "Building sdk-client"
-            if ! $YARN_EXEC nx run sdk-client:build:js; then
-                echo "Failed to build sdk-client"
-                has_errors=true
-            fi
         fi
     fi
 
@@ -190,8 +176,6 @@ restore_untracked_files() {
 original_pwd=${PWD}
 root_dir="$(git rev-parse --show-toplevel)"
 
-
-
 # Check for sdkman before running other initializations
 
 # This will ensure that the correct version of node and yarn is installed
@@ -278,6 +262,21 @@ fi
 
 # Check if sdk-client is affected
 check_sdk_client_affected
+
+# Check if there are changes in core-web/libs/sdk and run bump-sdk-versions.js if needed
+sdk_files_staged=$(echo "$staged_files" | grep -E '^core-web/libs/sdk/' || true)
+if [ -n "$sdk_files_staged" ]; then
+    echo "Changes detected in core-web/libs/sdk. Running bump-sdk-versions.js"
+    if ! node "${root_dir}/core-web/bump-sdk-versions.js"; then
+        echo "Failed to update versions"
+        has_errors=true
+    else
+        # Add all modified package.json files to staging
+        git add "${root_dir}/core-web/libs/sdk/"
+        git add "${root_dir}/examples/"
+        echo "Staged updated package.json files for SDKs and examples"
+    fi
+fi
 
 # Restore original working directory
 cd "${original_pwd}" || exit 1  # Exit if the directory does not exist
