Updated pre-commit script

diff --git a/core-web/.husky/pre-commit b/core-web/.husky/pre-commit
--- a/core-web/.husky/pre-commit
+++ b/core-web/.husky/pre-commit
@@ -17,11 +17,40 @@ NC='\033[0m' # No Color
 }
 
 check_sdk_client_affected() {
-    local affected=$(npx nx print-affected --select=projects)
-    if echo "$affected" | grep -q "sdk-client"; then
-        return 0
+    local YARN_EXEC="${root_dir}/installs/node/yarn/dist/bin/yarn"
+
+    local affected_projects=$(npx nx show projects --affected)
+    echo "Affected projects: $affected_projects"
+    if echo "$affected_projects" | grep -q "sdk-client"; then
+        echo "Building sdk-client"
+        if ! $YARN_EXEC nx run sdk-client:build:js; then
+            echo "Failed to build sdk-client"
+            has_errors=true
+        fi
+    fi
+
+    file_to_remove="${root_dir}/dotCMS/src/main/webapp/html/js/editor-js/package.json"
+    dir_to_remove="${root_dir}/dotCMS/src/main/webapp/html/js/editor-js/libs"
+
+    # Check if the file exists, then delete it
+    if [ -f "$file_to_remove" ]; then
+        rm "$file_to_remove"
+        echo "Removed $file_to_remove"
     else
-        return 1
+        echo "$file_to_remove does not exist"
+    fi
+
+    # Check if the directory exists, then delete it
+    if [ -d "$dir_to_remove" ]; then
+        rm -r "$dir_to_remove"
+        echo "Removed directory $dir_to_remove"
+    else
+        echo "$dir_to_remove does not exist"
+    fi
+
+    if ! git add "${root_dir}/dotCMS/src/main/webapp/html/js/editor-js/sdk-editor.js"; then
+        echo "Failed to stage computed sdk-client.js"
+        exit 1
     fi
 }
 
@@ -55,8 +84,8 @@ perform_frontend_fixes() {
     local add_to_index="$2"
     local file
 
-    local YARN_EXEC="${root_dir}/installs/node/yarn/dist/bin/yarn"
     local NODE_EXEC="${root_dir}/installs/node/node"
+    local YARN_EXEC="${root_dir}/installs/node/yarn/dist/bin/yarn"
 
     # Check if Yarn and Node executables are present
     if [[ ! -x "$YARN_EXEC" || ! -x "$NODE_EXEC" ]]; then
@@ -67,6 +96,7 @@ perform_frontend_fixes() {
     echo "Yarn version: $($YARN_EXEC --version 2>/dev/null)"
     echo "Node version: $($NODE_EXEC --version)"
     $YARN_EXEC config set registry https://dotcms-npm.b-cdn.net
+
     # Check if yarn.lock is present
     if ! $YARN_EXEC install; then
         echo "Failed to install dependencies with yarn install"
@@ -153,32 +183,6 @@ root_dir="$(git rev-parse --show-toplevel)"
 # from core-web/pom.xml and .nvmrc files are updated
 cd "${root_dir}" || exit 1
 
-# Check if sdk-client is affected
-if check_sdk_client_affected; then
-    # Run sdk-client build command
-    if ! npx nx run sdk-client:build:js; then
-        echo "Failed to build sdk-client"
-        exit 1
-    fi
-
-    # Remove specific file
-    file_to_remove="${root_dir}/dotCMS/src/main/webapp/html/js/editor-js/package.json"
-    if [ -f "$file_to_remove" ]; then
-        rm "$file_to_remove"
-        echo "Removed $file_to_remove"
-
-        # Stage the removal of the file
-        if ! git add "${root_dir}/dotCMS/src/main/webapp/html/js/editor-js/sdk-editor.js"; then
-            echo "Failed to stage the removal of sdk-client.js"
-            exit 1
-        fi
-    else
-        echo "$file_to_remove does not exist"
-    fi
-
-    cd "${core_web_dir}" || exit  # Ensure we return to core-web directory
-fi
-
 check_sdkman
 
 echo "Setting up Java"
@@ -256,6 +260,9 @@ core_web_files_untracked=$(echo "untracked_files" | grep -E '^core-web/' || true
 if [ -n "$core_web_files_untracked" ]; then
     perform_frontend_fixes "${core_web_files_untracked}" false
 fi
+
+# Check if sdk-client is affected
+check_sdk_client_affected
 
 # Restore original working directory
 cd "${original_pwd}" || exit 1  # Exit if the directory does not exist
