test ci

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -19,6 +19,94 @@ env:
   HEAD_REF: ${{ github.head_ref }}
 
 jobs:
+
+  check-all:
+    outputs:
+      name: ${{ steps.lint.outputs.name || steps.test.outputs.name || steps.build.outputs.name }}
+      status: ${{ steps.lint.outputs.status || steps.test.outputs.status || steps.build.outputs.status }}
+      color: ${{ steps.lint.outputs.color || steps.test.outputs.color || steps.build.outputs.color }}
+      message: ${{ steps.persist_results.outputs.message }}
+    runs-on: ubuntu-20.04
+
+    strategy:
+      matrix:
+        task:
+          - lint
+          - test
+          - build
+
+    name: Frontend Checks
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 18.13.0
+          cache: yarn
+          cache-dependency-path: 'core-web/yarn.lock'
+
+      - name: Install Dependencies
+        run: yarn --frozen-lockfile
+        working-directory: core-web
+
+      - name: Run Nx Affected ${{ matrix.task }}
+        working-directory: core-web
+        run: |
+          if [ "${{ matrix.task }}" = "test" ] || [ "${{ matrix.task }}" = "lint" ]; then
+            
+            exclude_option="--exclude=${{ env.EXCLUDED_PROJECTS }}"
+            if ! (npx nx affected --target=${{ matrix.task }} --base=origin/master --head=HEAD --parallel $exclude_option) then
+              echo "name=:x: ${{ matrix.task }}" >>$GITHUB_OUTPUT
+              echo "status=failure" >>$GITHUB_OUTPUT
+              echo "color=#ff2400" >>$GITHUB_OUTPUT
+              exit 1;
+            fi
+          elif [ "${{ matrix.task }}" = "build" ]; then
+            
+            if ! (npx nx build dotcms-ui) then
+              echo "name=:x: ${{ matrix.task }}" >>$GITHUB_OUTPUT
+              echo "status=failure" >>$GITHUB_OUTPUT
+              echo "color=#ff2400" >>$GITHUB_OUTPUT
+              exit 1;
+            fi
+          fi
+
+#      - name: Lint2
+#        id: lint1
+#        working-directory: core-web
+#        run: |
+#          if ! (npx nx affected --target=lint --base=origin/master --head=HEAD --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
+#            echo "name=:x: Lint" >>$GITHUB_OUTPUT
+#            echo "status=failure" >>$GITHUB_OUTPUT
+#            echo "color=#ff2400" >>$GITHUB_OUTPUT
+#            exit 1;
+#          fi
+#
+#      - name: Test
+#        id: test
+#        working-directory: core-web
+#        run: |
+#          if ! (npx nx affected --target=test --base=origin/master --head=HEAD --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
+#            echo "name=:x: Test" >>$GITHUB_OUTPUT
+#            echo "status=failure" >>$GITHUB_OUTPUT
+#            echo "color=#ff2400" >>$GITHUB_OUTPUT
+#            exit 1;
+#          fi
+#
+#      - name: Build
+#        id: build
+#        working-directory: core-web
+#        run:  |
+#          if ! (npx nx build dotcms-ui) then
+#            echo "name=:x: Build" >>$GITHUB_OUTPUT
+#            echo "status=failure" >>$GITHUB_OUTPUT
+#            echo "color=#ff2400" >>$GITHUB_OUTPUT
+#            exit 1;
+#          fi
 #  sonar:
 #    outputs:
 #      message: ${{ steps.persist_results.outputs.message }}
@@ -87,87 +175,6 @@ jobs:
 #          SLACK_TITLE: "SonarQube: ${{ needs.sonar.outputs.status }}"
 #          SLACK_MESSAGE: ${{ needs.sonar.outputs.message }}
 #          SLACK_FOOTER: ${{ env.PULL_REQUEST_URL }} - ${{ secrets.SONAR_HOST_URL }}/${{ env.SONAR_BRANCH_REPORT }}
-  check-all:
-    outputs:
-      name: ${{ steps.lint.outputs.name || steps.test.outputs.name || steps.build.outputs.name }}
-      status: ${{ steps.lint.outputs.status || steps.test.outputs.status || steps.build.outputs.status }}
-      color: ${{ steps.lint.outputs.color || steps.test.outputs.color || steps.build.outputs.color }}
-      message: ${{ steps.persist_results.outputs.message }}
-    runs-on: ubuntu-20.04
-
-    strategy:
-      matrix:
-        task:
-          - lint
-          - test
-          - build
-
-    name: Frontend Checks
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
-          node-version: 18.13.0
-          cache: yarn
-          cache-dependency-path: 'core-web/yarn.lock'
-
-      - name: Install Dependencies
-        run: yarn --frozen-lockfile
-        working-directory: core-web
-
-      - name: Run Nx Affected ${{ matrix.task }}
-        working-directory: core-web
-        run: |
-          exclude_option=""
-          if [ "${{ matrix.task }}" = "test" ] || [ "${{ matrix.task }}" = "lint" ]; then
-            exclude_option="--exclude=${{ env.EXCLUDED_PROJECTS }}"
-          fi
-
-          if ! (npx nx affected --target=${{ matrix.task }} --base=origin/master --head=HEAD --parallel $exclude_option) then
-            echo "name=:x: ${{ matrix.task }}" >>$GITHUB_OUTPUT
-            echo "status=failure" >>$GITHUB_OUTPUT
-            echo "color=#ff2400" >>$GITHUB_OUTPUT
-            exit 1;
-          fi
-
-#      - name: Lint2
-#        id: lint1
-#        working-directory: core-web
-#        run: |
-#          if ! (npx nx affected --target=lint --base=origin/master --head=HEAD --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
-#            echo "name=:x: Lint" >>$GITHUB_OUTPUT
-#            echo "status=failure" >>$GITHUB_OUTPUT
-#            echo "color=#ff2400" >>$GITHUB_OUTPUT
-#            exit 1;
-#          fi
-#
-#      - name: Test
-#        id: test
-#        working-directory: core-web
-#        run: |
-#          if ! (npx nx affected --target=test --base=origin/master --head=HEAD --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
-#            echo "name=:x: Test" >>$GITHUB_OUTPUT
-#            echo "status=failure" >>$GITHUB_OUTPUT
-#            echo "color=#ff2400" >>$GITHUB_OUTPUT
-#            exit 1;
-#          fi
-#
-#      - name: Build
-#        id: build
-#        working-directory: core-web
-#        run:  |
-#          if ! (npx nx build dotcms-ui) then
-#            echo "name=:x: Build" >>$GITHUB_OUTPUT
-#            echo "status=failure" >>$GITHUB_OUTPUT
-#            echo "color=#ff2400" >>$GITHUB_OUTPUT
-#            exit 1;
-#          fi
-
 #  notify-check-all:
 #    runs-on: ubuntu-20.04
 #    name: Notify Slack
