Add SonarQube GitHub Action

diff --git a/.github/workflows/frontend.yml b/.github/workflows/frontend.yml
--- a/.github/workflows/frontend.yml
+++ b/.github/workflows/frontend.yml
@@ -18,76 +18,87 @@ env:
   IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
   HEAD_REF: ${{ github.head_ref }}
 jobs:
-  check-all:
-    outputs:
-      name: ${{ steps.lint.outputs.name || steps.test.outputs.name || steps.build.outputs.name }}
-      status: ${{ steps.lint.outputs.status || steps.test.outputs.status || steps.build.outputs.status }}
-      color: ${{ steps.lint.outputs.color || steps.test.outputs.color || steps.build.outputs.color }}
-      message: ${{ steps.persist_results.outputs.message }}
-    runs-on: ubuntu-20.04 # the image our job will run on
-    name: Frontend Checks # the name that will appear on the Actions UI
-    steps: # what steps it will perform
-      - uses: actions/checkout@v3 # checkout whatever branch the PR is using
+  sonar:
+    runs-on: ubuntu-20.04
+    name: SonarQube
+    steps:
+      - uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - uses: actions/setup-node@v3
-        with:
-          node-version: 16.14.2
-          cache: npm
-          cache-dependency-path: core-web/package-lock.json
-      - uses: bahmutov/npm-install@v1 # trigger an `npm install`
-        with:
-          working-directory: core-web
-      - name: Lint
-        id: lint
-        working-directory: core-web
-        run: |
-          if ! (npx nx affected --target=lint --base=origin/master --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
-            echo "name=:x: Lint" >>$GITHUB_OUTPUT
-            echo "status=failure" >>$GITHUB_OUTPUT
-            echo "color=#ff2400" >>$GITHUB_OUTPUT
-            exit 1;
-          fi
-      - name: Test
-        id: test
-        working-directory: core-web
-        run: |
-          if ! (npx nx affected --target=test --base=origin/master --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
-            echo "name=:x: Test" >>$GITHUB_OUTPUT
-            echo "status=failure" >>$GITHUB_OUTPUT
-            echo "color=#ff2400" >>$GITHUB_OUTPUT
-            exit 1;
-          fi
-      - name: Push Tests to GitHub
-        id: persist_results
-        if: success() || failure()
-        run: |
-          chmod +x .cicd/github.sh && source .cicd/github.sh
-          persistResults
-          echo "message=$(logResults)" >>$GITHUB_OUTPUT
-      - name: Build
-        id: build
-        working-directory: core-web
-        run:  |
-          if ! (npx nx build dotcms-ui) then
-            echo "name=:x: Build" >>$GITHUB_OUTPUT
-            echo "status=failure" >>$GITHUB_OUTPUT
-            echo "color=#ff2400" >>$GITHUB_OUTPUT
-            exit 1;
-          fi
-  notify:
-    runs-on: ubuntu-20.04 # the image our job will run on
-    name: Notify Slack
-    needs: check-all
-    if: always()
-    steps:
-      - name: Slack Notification
-        uses: rtCamp/action-slack-notify@v2
+      - uses: sonarsource/sonarqube-scan-action@master
         env:
-          SLACK_WEBHOOK: ${{ secrets.UI_SLACK_WEBHOOK }}
-          SLACK_USERNAME: dotBot
-          SLACK_ICON: https://avatars.slack-edge.com/2020-09-21/1362682893351_5b474f175640cf5f5912_72.png
-          SLACK_COLOR: ${{ needs.check-all.outputs.color && needs.check-all.outputs.color || '#5E7D00' }}
-          SLACK_TITLE: "${{ needs.check-all.outputs.name && needs.check-all.outputs.name || ':white_check_mark: Frontend Checks' }}: (${{ needs.check-all.outputs.status && needs.check-all.outputs.status || 'Success' }})"
-          SLACK_MESSAGE: ${{ needs.check-all.outputs.message && needs.check-all.outputs.message || 'Everything went well, ready to merge'}} 
-          SLACK_FOOTER: ${{ env.PULL_REQUEST_URL }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_DOTCMS_UI }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+  # check-all:
+  #   outputs:
+  #     name: ${{ steps.lint.outputs.name || steps.test.outputs.name || steps.build.outputs.name }}
+  #     status: ${{ steps.lint.outputs.status || steps.test.outputs.status || steps.build.outputs.status }}
+  #     color: ${{ steps.lint.outputs.color || steps.test.outputs.color || steps.build.outputs.color }}
+  #     message: ${{ steps.persist_results.outputs.message }}
+  #   runs-on: ubuntu-20.04
+  #   name: Frontend Checks
+  #   steps: # what steps it will perform
+  #     - uses: actions/checkout@v3 # checkout whatever branch the PR is using
+  #       with:
+  #         fetch-depth: 0
+  #     - uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 16.14.2
+  #         cache: npm
+  #         cache-dependency-path: core-web/package-lock.json
+  #     - uses: bahmutov/npm-install@v1 # trigger an `npm install`
+  #       with:
+  #         working-directory: core-web
+  #     - name: Lint
+  #       id: lint
+  #       working-directory: core-web
+  #       run: |
+  #         if ! (npx nx affected --target=lint --base=origin/master --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
+  #           echo "name=:x: Lint" >>$GITHUB_OUTPUT
+  #           echo "status=failure" >>$GITHUB_OUTPUT
+  #           echo "color=#ff2400" >>$GITHUB_OUTPUT
+  #           exit 1;
+  #         fi
+  #     - name: Test
+  #       id: test
+  #       working-directory: core-web
+  #       run: |
+  #         if ! (npx nx affected --target=test --base=origin/master --parallel --exclude=${{ env.EXCLUDED_PROJECTS }}) then
+  #           echo "name=:x: Test" >>$GITHUB_OUTPUT
+  #           echo "status=failure" >>$GITHUB_OUTPUT
+  #           echo "color=#ff2400" >>$GITHUB_OUTPUT
+  #           exit 1;
+  #         fi
+  #     - name: Push Tests to GitHub
+  #       id: persist_results
+  #       if: success() || failure()
+  #       run: |
+  #         chmod +x .cicd/github.sh && source .cicd/github.sh
+  #         persistResults
+  #         echo "message=$(logResults)" >>$GITHUB_OUTPUT
+  #     - name: Build
+  #       id: build
+  #       working-directory: core-web
+  #       run:  |
+  #         if ! (npx nx build dotcms-ui) then
+  #           echo "name=:x: Build" >>$GITHUB_OUTPUT
+  #           echo "status=failure" >>$GITHUB_OUTPUT
+  #           echo "color=#ff2400" >>$GITHUB_OUTPUT
+  #           exit 1;
+  #         fi
+  # notify:
+  #   runs-on: ubuntu-20.04
+  #   name: Notify Slack
+  #   needs: check-all
+  #   if: always()
+  #   steps:
+  #     - name: Slack Notification
+  #       uses: rtCamp/action-slack-notify@v2
+  #       env:
+  #         SLACK_WEBHOOK: ${{ secrets.UI_SLACK_WEBHOOK }}
+  #         SLACK_USERNAME: dotBot
+  #         SLACK_ICON: https://avatars.slack-edge.com/2020-09-21/1362682893351_5b474f175640cf5f5912_72.png
+  #         SLACK_COLOR: ${{ needs.check-all.outputs.color && needs.check-all.outputs.color || '#5E7D00' }}
+  #         SLACK_TITLE: "${{ needs.check-all.outputs.name && needs.check-all.outputs.name || ':white_check_mark: Frontend Checks' }}: (${{ needs.check-all.outputs.status && needs.check-all.outputs.status || 'Success' }})"
+  #         SLACK_MESSAGE: ${{ needs.check-all.outputs.message && needs.check-all.outputs.message || 'Everything went well, ready to merge'}} 
+  #         SLACK_FOOTER: ${{ env.PULL_REQUEST_URL }}
