test webcomponents results

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -102,11 +102,11 @@ jobs:
         run: |
           cd core-web
           npm run build:prod
-      - name: Running tests
+      - name: Running dotcms-ui tests
         id: test_run
         run: |
           cd core-web
-          if ! (npx nx run-many --target=test --projects=dotcms-ui,dotcms-webcomponents) then
+          if ! (npx nx run dotcms-ui:test) then
             echo "::set-output name=status::failure";
             echo "::set-output name=color::#ff2400";
             exit 1;
@@ -121,6 +121,38 @@ jobs:
           chmod +x .cicd/github.sh && source .cicd/github.sh
           persistResults
           echo "::set-output name=message::$(logResults)";
+      - name: Slack Notification
+        if: success() || failure()
+        uses: rtCamp/action-slack-notify@v2
+        env:
+          SLACK_WEBHOOK: ${{ secrets.UI_SLACK_WEBHOOK }}
+          SLACK_USERNAME: dotBot
+          SLACK_ICON: https://avatars.slack-edge.com/2020-09-21/1362682893351_5b474f175640cf5f5912_72.png
+          SLACK_COLOR: ${{ steps.test_run.outputs.color }}
+          SLACK_TITLE: "Report: (${{ steps.test_run.outputs.status }})"
+          SLACK_MESSAGE: ${{ steps.persist_results.outputs.message }}
+          SLACK_FOOTER: ${{ env.PULL_REQUEST_URL }}
+
+      - name: Running dotcms-webcomponents tests
+        id: test_run2
+        run: |
+          cd core-web
+          if ! (npx nx run dotcms-webcomponents:test) then
+            echo "::set-output name=status::failure";
+            echo "::set-output name=color::#ff2400";
+            exit 1;
+          else
+            echo "::set-output name=status::success";
+            echo "::set-output name=color::#5E7D00";
+          fi
+      - name: Push Tests to GitHub
+        id: persist_results
+        if: success() || failure()
+        run: |
+          chmod +x .cicd/github.sh && source .cicd/github.sh
+          persistWebComponentsTestResults
+          echo "::set-output name=message::$(logResults)";
+
       - name: Slack Notification
         if: success() || failure()
         uses: rtCamp/action-slack-notify@v2
