noop

diff --git a/.github/workflows/maven-build-docker-image.yml b/.github/workflows/maven-build-docker-image.yml
--- a/.github/workflows/maven-build-docker-image.yml
+++ b/.github/workflows/maven-build-docker-image.yml
@@ -120,55 +120,53 @@ jobs:
       - name: Set Common Vars
         id: set-common-vars
         run: |
-          build_version=master
           build_properties=${DOCKER_BUILD_CONTEXT}/context/maven/dotserver/tomcat-9.0.60/webapps/ROOT/WEB-INF/classes/build.properties
+          if [[ ! -f ${build_properties} ]]; then
+            echo 'Could not find build.properties, aborting'
+            exit 1
+          fi
           
-          if [[ -f ${build_properties} ]]; then
-            version=$(cat ${build_properties} | grep version | cut -d'=' -f2)
-            if [[ ! ${version} =~ ^[0-9]{1}.[0-9]{1}.[0-9]{1}-SNAPSHOT$ ]]; then
-              build_version=${build_version}
-            fi
+          echo 'Build properties:'
+          cat ${build_properties}
           
-            build_hash=$(cat ${build_properties} | grep revision | cut -d'=' -f2)
-            if [[ ! ${build_hash} =~ ^[0-9a-f]{7}$ ]]; then
-              build_hash=$(git log -1 --pretty=%h)
-              build_hash=${build_hash::7}
-            fi
+          version=$(cat ${build_properties} | grep version | cut -d'=' -f2)
+          build_hash=$(cat ${build_properties} | grep revision | cut -d'=' -f2)
+          if [[ ! ${build_hash} =~ ^[0-9a-f]{7}$ ]]; then
+            build_hash=$(git log -1 --pretty=%h)
+            build_hash=${build_hash::7}
           fi
           
           build_id=${{ inputs.ref }}
-          
           is_trunk=false
-          if [[ "${build_id}" == 'master' || ${build_id} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then
+          if [[ "${build_id}" == 'master' || ${build_id} =~ ^v[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then
             is_trunk=true
           fi
           
           is_lts=false
-          if [[ ${build_version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts(_v[0-9]{2})?$ ]]; then
+          if [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts(_v[0-9]{2})?$ ]]; then
             is_lts=true
           fi
           
-          version=${build_version}
           is_snapshot=false
           is_release=false
           is_latest=false
           is_custom=false
           is_trunk_snapshot=false
           
-          if [[ ${build_version} =~ ^[0-9]{1}.[0-9]{1}.[0-9]{1}-SNAPSHOT$ ]]; then
+          if [[ ${version} =~ ^[0-9]{1}.[0-9]{1}.[0-9]{1}-SNAPSHOT$ ]]; then
             is_snapshot=true
 
             if [[ "${is_trunk}" == 'true' ]]; then
               is_trunk_snapshot=true
               version=${build_id}
             fi
-          elif [[ ${build_version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}$ ]]; then
+          elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}$ ]]; then
             is_release=true
             is_latest=true
-          elif [[ ${build_version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then
+          elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts$ ]]; then
             is_snapshot=true
             version=${build_id}
-          elif [[ ${build_version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts_v[0-9]{2}$ ]]; then
+          elif [[ ${version} =~ ^[0-9]{2}.[0-9]{2}.[0-9]{2}_lts_v[0-9]{2}$ ]]; then
             is_release=true
           else
             is_custom=true
