Clean-up runner (#27504)

diff --git a/.github/workflows/maven-cicd-pipeline.yml b/.github/workflows/maven-cicd-pipeline.yml
--- a/.github/workflows/maven-cicd-pipeline.yml
+++ b/.github/workflows/maven-cicd-pipeline.yml
@@ -20,7 +20,7 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
   cancel-in-progress: true
 env:
-  JVM_TEST_MAVEN_OPTS: "-e -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
+  JVM_TEST_MAVEN_OPTS: "-e -B --no-transfer-progress -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
   DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
   REGISTRY: ghcr.io
   IMAGE_NAME: dotcms/dotcms_test
@@ -34,18 +34,53 @@ jobs:
     permissions:
       pull-requests: read
     outputs:
-      backend: ${{ steps.filter.outputs.backend }}
-      frontend: ${{ steps.filter.outputs.frontend }}
-      build: ${{ steps.filter.outputs.build }}
-      jvm_unit_test: ${{ steps.filter.outputs.jvm_unit_test }}
+      backend: ${{ steps.filter-rewrite.outputs.backend }}
+      frontend: ${{ steps.filter-rewrite.outputs.frontend }}
+      build: ${{ steps.filter-rewrite.outputs.build }}
+      jvm_unit_test: ${{ steps.filter-rewrite.outputs.jvm_unit_test }}
+      cli: ${{ steps.filter-rewrite.outputs.cli }}
     steps:
       - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - uses: dorny/paths-filter@v2
+      - uses: dorny/paths-filter@v2.11.1
         id: filter
         with:
           filters: .github/filters.yaml
+          list-files: 'escape'
+      - name: Rewrite Filter
+        id: filter-rewrite
+        run: |
+          frontend=${{ steps.filter.outputs.frontend }}
+          cli=${{ steps.filter.outputs.cli }}
+          backend=${{ steps.filter.outputs.backend }}
+          build=${{ steps.filter.outputs.build }}
+          jvm_unit_test=${{ steps.filter.outputs.jvm_unit_test }} 
+          
+          is_backend=false
+          backend_files=( ${{ steps.filter.outputs.backend_files }} )
+          for backend_file in "${backend_files[@]}"
+          do
+            echo "Evaluating ${backend_file}"
+            if [[ ! ${backend_file} =~ ^dotCMS/src/main/webapp/html/.*\.(js|css)$ ]]; then
+              echo "Backend file ${backend_file} is not a frontend file... aborting search"
+              is_backend=true
+              break
+            fi
+          done
+          
+          backend=${is_backend}
+          [[ "${backend}" == 'true' ]] && build=true && jvm_unit_test=true
+          
+          echo "frontend=${frontend}"
+          echo "cli=${cli}"
+          echo "backend=${backend}"
+          echo "build=${build}"
+          echo "jvm_unit_test=${jvm_unit_test}"
+          
+          echo "frontend=${frontend}" >> $GITHUB_OUTPUT
+          echo "cli=${cli}" >> $GITHUB_OUTPUT
+          echo "backend=${backend}" >> $GITHUB_OUTPUT
+          echo "build=${build}" >> $GITHUB_OUTPUT
+          echo "jvm_unit_test=${jvm_unit_test}" >> $GITHUB_OUTPUT
 
   #
   # Initial JDK 11 Build
@@ -65,7 +100,8 @@ jobs:
       contents: read
       packages: write
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/cleanup-runner
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -83,13 +119,13 @@ jobs:
         with:
           version: latest
           platforms: ${{ env.DOCKER_PLATFORMS }}
+          driver-opts: |
+            image=moby/buildkit:v0.12.2
       - name: Docker Hub login
         uses: docker/login-action@v3.0.0
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
-          driver-opts: |
-            image=moby/buildkit:v0.12.2
       - id: docker-login
         name: Login to GHCR
         uses: docker/login-action@v3.0.0
@@ -197,7 +233,8 @@ jobs:
             maven_args: ""
           }
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/cleanup-runner
       - name: Set up JDK ${{ matrix.java.name }}
         uses: actions/setup-java@v3
         with:
@@ -210,7 +247,7 @@ jobs:
         shell: bash
       - name: Restore Maven Repository
         id: cache-maven
-        uses: actions/cache@v3
+        uses: actions/cache/restore@v3
         with:
           path: ~/.m2/repository
           key: mavencore-${{ steps.get-date.outputs.date }}-${{ github.run_id }}
@@ -238,6 +275,81 @@ jobs:
             LICENSE
           retention-days: 2
 
+  linux-cli-tests:
+    name: CLI Tests - JDK ${{matrix.java.name}}
+    runs-on: ubuntu-20.04
+    if: ${{ needs.changes.outputs.cli == 'true' || needs.changes.outputs.backend == 'true' }}
+    needs: [ changes,build-jdk11 ]
+    timeout-minutes: 240
+    env:
+      MAVEN_OPTS: -Xmx2048m
+    strategy:
+      fail-fast: true
+      matrix:
+        java:
+          - {
+            name: "11",
+            java-version: 11,
+            distribution: 'temurin',
+            maven_args: ""
+          }
+    steps:
+      - uses: actions/checkout@v3
+      - name: Set up JDK ${{ matrix.java.name }}
+        uses: actions/setup-java@v3
+        with:
+          java-version: ${{ matrix.java.java-version }}
+          distribution: ${{ matrix.java.distribution }}
+      - name: Get Date
+        id: get-date
+        run: |
+          echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT
+        shell: bash
+      - name: Restore Maven Repository
+        id: cache-maven
+        uses: actions/cache/restore@v3
+        with:
+          path: ~/.m2/repository
+          key: mavencore-${{ steps.get-date.outputs.date }}-${{ github.run_id }}
+      - id: docker-login
+        name: Login to GHCR
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - id: prepare-license
+        name: Prepare license
+        env:
+          DOTCMS_LICENSE_KEY: ${{ secrets.DOTCMS_LICENSE }}
+        run: |
+          DOTCMS_LICENSE_PATH=${GITHUB_WORKSPACE}/tools/dotcms-cli/target/license
+          mkdir -p ${DOTCMS_LICENSE_PATH}
+          echo "${DOTCMS_LICENSE_KEY}" > ${DOTCMS_LICENSE_PATH}/license.dat
+          echo "DOTCMS_LICENSE_FILE=${DOTCMS_LICENSE_PATH}/license.dat" >> "$GITHUB_ENV"
+      - name: Build
+        run: eval ./mvnw -Dprod $JVM_TEST_MAVEN_OPTS -Dtestcontainers.docker.image=${{ needs.build-jdk11.outputs.docker-tag }} -pl :dotcms-api-data-model,:dotcms-cli verify ${{ matrix.java.maven_args}}
+      - name: Prepare reports archive (if maven failed)
+        if: failure()
+        shell: bash
+        run: find . -name '*-reports' -type d | tar -czf test-reports.tgz -T -
+      - name: Upload reports Archive (if maven failed)
+        uses: actions/upload-artifact@v3
+        if: failure()
+        with:
+          name: test-reports-cli-jvm${{matrix.java.name}}
+          path: 'test-reports.tgz'
+      - name: cli-tests
+        uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: "build-reports-test-cli - JDK ${{matrix.java.name}}"
+          path: |
+            **/target/*-reports/TEST-*.xml
+            target/build-report.json
+            LICENSE
+          retention-days: 2
+
   #
   # Run Frontend Tests
   #
@@ -250,10 +362,8 @@ jobs:
     env:
       MAVEN_OPTS: -Xmx2048m
     steps:
-      - uses: actions/checkout@v3
-      - name: apt clean
-        shell: bash
-        run: sudo apt-get clean
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/cleanup-runner
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
@@ -266,7 +376,7 @@ jobs:
         shell: bash
       - name: Restore Maven Repository
         id: cache-maven
-        uses: actions/cache@v3
+        uses: actions/cache/restore@v3
         with:
           path: ~/.m2/repository
           key: mavencore-${{ steps.get-date.outputs.date }}-${{ github.run_id }}
@@ -296,7 +406,7 @@ jobs:
         shell: bash
         env:
           NODE_CACHE_HIT: ${{ steps.cache-node-modules.outputs.cache-hit }}
-        run: eval ./mvnw -Dprod $JVM_TEST_MAVEN_OPTS -Dskip.npm.install=${NODE_CACHE_HIT} $JVM_TEST_MAVEN_OPTS -pl :dotcms-core-web test
+        run: eval ./mvnw -Dprod -Dskip.npm.install=${NODE_CACHE_HIT} $JVM_TEST_MAVEN_OPTS -pl :dotcms-core-web test
       - name: Prepare failure archive (if maven failed)
         if: failure()
         shell: bash
@@ -361,10 +471,8 @@ jobs:
               maven_args: '"-Dit.test=MainSuite2b" -Dit.test.forkcount=1'
           }
     steps:
-      - uses: actions/checkout@v3
-      - name: apt clean
-        shell: bash
-        run: sudo apt-get clean
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/cleanup-runner
       - name: Set up IT Tests ${{ matrix.java.name }} ${{ matrix.suites.name }}
         uses: actions/setup-java@v3
         with:
@@ -385,14 +493,14 @@ jobs:
         shell: bash
       - name: Restore Maven Repository
         id: cache-maven
-        uses: actions/cache@v3
+        uses: actions/cache/restore@v3
         with:
           path: ~/.m2/repository
           key: mavencore-${{ steps.get-date.outputs.date }}-${{ github.run_id }}
       - name: Build
         env:
           DOT_DOTCMS_LICENSE: ${{ secrets.DOTCMS_LICENSE }}
-        run: eval ./mvnw -Dit-tests -Dprod $JVM_TEST_MAVEN_OPTS verify -pl :dotcms-integration ${{ matrix.suites.maven_args}} ${{ matrix.java.maven_args}}
+        run: eval ./mvnw -Dprod $JVM_TEST_MAVEN_OPTS verify -pl :dotcms-integration ${{ matrix.suites.maven_args}} ${{ matrix.java.maven_args}}
       - name: Prepare reports archive (if maven failed)
         if: failure()
         shell: bash
@@ -417,17 +525,16 @@ jobs:
   linux-postman-tests:
     name: Run Postman Tests - ${{matrix.collection_group}}
     runs-on: ubuntu-latest
-    needs: build-jdk11
-    if: "github.repository == 'dotCMS/core' || !endsWith(github.ref, '/master')"
+    needs: [build-jdk11, changes]
+    if: ${{ needs.changes.outputs.backend == 'true' }}
     strategy:
       fail-fast: false
       matrix:
-        collection_group: [ 'graphql', 'workflow', 'template', 'page', 'container', 'pp', 'experiment', 'default' ]
+        collection_group: [ 'category-container', 'content', 'experiment', 'graphql', 'page', 'pp', 'template', 'workflow',  'default' ]
     steps:
-      - id: fetch-core
-        name: Fetch Core Repo
-        uses: actions/checkout@v3
-      - run: npm install --location=global newman
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/cleanup-runner
+      - run: sudo npm install --location=global newman@5.3.2 newman-reporter-htmlextra@1.23.0
       - id: docker-login
         name: Login to GHCR
         uses: docker/login-action@v3.0.0
@@ -440,28 +547,39 @@ jobs:
         with:
           current: ${{ matrix.collection_group }}
       - name: Prepare license
+        id: prepare-license
         run: |
-          mkdir -p dotcms-postman/license
-          touch dotcms-postman/license/license.dat
-          echo "${{ secrets.DOTCMS_LICENSE }}" > dotcms-postman/license/license.dat
-          chmod 777 dotcms-postman/license/license.dat
+          postman_dir=${{ github.workspace }}/dotcms-postman
+          docker_volumes_dir=${postman_dir}/target/docker-volumes
+          [[ -d ${docker_volumes_dir} ]] && rm -rf ${docker_volumes_dir}
+          
+          dotcms_volumes_dir=${docker_volumes_dir}/dotcms
+          license_dir=${dotcms_volumes_dir}/license
+          
+          mkdir -p ${license_dir}
+          
+          license_file=${license_dir}/license.dat
+          touch ${license_file}
+          echo "${{ secrets.DOTCMS_LICENSE }}" > ${license_file}
+          chmod -R 777 ${license_dir}
       - id: run-postman-tests
         name: Run Postman Tests
         timeout-minutes: 90
         run: |
-          collections="${{ steps.resolve-postman-collections.outputs.collections_to_run }}"
-          #export DOTCMS_IMAGE='dotcms/dotcms:latest'
-          export DOTCMS_IMAGE="${{ needs.build-jdk11.outputs.docker-tag }}"
-
-          cmd="./mvnw $JVM_TEST_MAVEN_OPTS verify -pl :dotcms-postman -Dpostman.collections=\"${collections}\""
-          echo "Running command: $cmd"
-          eval $cmd
+          ./mvnw -Dpostman-tests -Dprod $JVM_TEST_MAVEN_OPTS verify \
+            -pl :dotcms-postman \
+            -Dpostman.collections="${{ steps.resolve-postman-collections.outputs.collections_to_run }}"
+          pec=$?
+          [[ pec -eq 0 ]] || exit pec
         env:
-          JVM_TEST_MAVEN_OPTS: "-e -B"
+          DOTCMS_IMAGE: ${{ needs.build-jdk11.outputs.docker-tag }}
       - name: Prepare reports archive (if maven failed)
         if: failure()
         shell: bash
-        run: find . -name '*-reports' -type d | tar -czf test-reports.tgz -T -
+        run: |
+          find . -name '*-reports' -type d
+          tree ./dotcms-postman
+          find . -name '*-reports' -type d | tar -czf test-reports.tgz -T -
       - name: Upload failure Archive (if maven failed)
         uses: actions/upload-artifact@v3
         if: failure()
@@ -472,23 +590,59 @@ jobs:
         uses: actions/upload-artifact@v3
         if: always()
         with:
-          name: "build-reports-postman-tests - ${{ matrix.collection_group }}"
+          name: "build-reports-test-postman - ${{ matrix.collection_group }}"
           path: |
-            **/target/*-reports/TEST-*.xml
+            **/dotcms-postman/target/postman-reports/TEST-*.xml
             target/build-report.json
             LICENSE
           retention-days: 2
-
+  sonarqube:
+    name: SonarQube Scan
+    runs-on: ubuntu-latest
+    needs: [build-jdk11]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: ./.github/actions/cleanup-runner
+      - name: Set up JDK 11
+        uses: actions/setup-java@v3
+        with:
+          java-version: 11
+          distribution: 'temurin'
+      - name: Get Date
+        id: get-date
+        run: |
+          echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT
+        shell: bash
+      - name: Restore Maven Repository
+        id: cache-maven
+        uses: actions/cache/restore@v3
+        with:
+          path: ~/.m2/repository
+          key: mavencore-${{ steps.get-date.outputs.date }}-${{ github.run_id }}
+      - name: Cache SonarQube packages
+        uses: actions/cache@v1
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
+      - name: Maven Build No Test
+        shell: bash
+        run: |
+          ./mvnw $JVM_TEST_MAVEN_OPTS compile sonar:sonar -Dsonar.projectKey=dotCMS_core_AYSbIemxK43eThAXTlt- -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN
+        env:
+          MAVEN_OPTS: "-Xmx2048m"
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
   clean-up:
     name: Clean up
     runs-on: ubuntu-latest
-    needs: linux-postman-tests
+    needs: [build-jdk11, linux-postman-tests]
     if: (success() || failure()) && (github.repository == 'dotCMS/core' || !endsWith(github.ref, '/master'))
     steps:
-      - id: fetch-core
-        name: Fetch Core Repo
-        uses: actions/checkout@v3
-
+      - uses: actions/checkout@v4
       - id: cleanup-package
         name: Clean up CICD packages
         uses: ./.github/actions/cleanup-gh-packages
@@ -502,7 +656,7 @@ jobs:
   prepare-report-data:
     name: Prepare Report Data
     runs-on: ubuntu-20.04
-    needs: [ build-jdk11,linux-jvm-tests,linux-integration-tests,linux-frontend-tests,linux-postman-tests ]
+    needs: [ build-jdk11,linux-jvm-tests,linux-integration-tests,linux-frontend-tests,linux-cli-tests,linux-postman-tests,sonarqube ]
     if: always()
     outputs:
       aggregate_status: ${{ steps.prepare-workflow-data.outputs.aggregate_status }}
