Allowing to publish docker image nicely

diff --git a/.github/workflows/publish-docker-image-on-release.yml b/.github/workflows/publish-docker-image-on-release.yml
--- a/.github/workflows/publish-docker-image-on-release.yml
+++ b/.github/workflows/publish-docker-image-on-release.yml
@@ -3,63 +3,94 @@ on:
   push:
     branches:
       - release-*
+  repository_dispatch:
+    types:
+      - enterprise-update
 jobs:
   publish_image:
     name: Publish DotCMS docker image on release push
     runs-on: ubuntu-latest
     steps:
-      - name: GITHUB CONTEXT
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: echo "$GITHUB_CONTEXT"
-        if: env.DEBUG == 'true'
+      - name: Process Params
+        run: |
+          if [[ "${{ github.event_name }}" == 'repository_dispatch' ]]; then
+            BUILD_ID=${{ github.event.client_payload.build_id }}
+          else
+            BUILD_ID=$(basename "${{ github.ref }}")
+          fi
+
+          if [[ -z "${BUILD_ID}" ]]; then
+            echo 'Could not resolve BUILD_ID, aborting'
+            exit 1
+          else
+            echo "Found BUILD_ID: ${BUILD_ID}"
+          fi
+
+          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
       - name: Checkout core
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ env.BUILD_ID }}
+          token: ${{ secrets.CICD_GITHUB_TOKEN }}
+          submodules: recursively
       - name: Set Common Vars
         run: |
-          BUILD_ID=$(basename "${{ github.ref }}")
           BUILD_HASH=$(git log -1 --pretty=%h)
           eval $(cat dotCMS/gradle.properties| grep dotcmsReleaseVersion)
           DOTCMS_VERSION="${dotcmsReleaseVersion}"
-          jobRun=true
+
           if [[ ${BUILD_ID} =~ ^release-[0-9]{2}.[0-9]{2}(.[0-9]{1,2})?$ ]]; then
             jobRun=true
           else
             jobRun=false
           fi
 
-          echo "BUILD_ID=${BUILD_ID}" >> $GITHUB_ENV
           echo "BUILD_HASH=${BUILD_HASH}" >> $GITHUB_ENV
           echo "DOTCMS_VERSION=${DOTCMS_VERSION}" >> $GITHUB_ENV
           echo "jobRun=${jobRun}" >> $GITHUB_ENV
       - name: Discover docker tags
         id: discover-docker-tags
-        uses: dotcms/discover-docker-tags-action@main
+        uses: dotcms/discover-docker-tags-action@v2.0
         with:
           version: ${{ env.DOTCMS_VERSION }}
           hash: ${{ env.BUILD_HASH }}
           label: 'SNAPSHOT'
           update_stable: false
           also_latest: false
+          image_name: dotcms/dotcms
         if: env.jobRun == 'true'
-      - name: Publish docker image
-        id: publish-docker-image
-        uses: dotcms/publish-docker-image-action@main
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2.1.0
         with:
-          dot_cicd_branch: master
-          build_id: ${{ env.BUILD_ID }}
+          platforms: amd64,arm64
+      - name: Docker Setup Buildx
+        uses: docker/setup-buildx-action@v2.2.1
+        with:
+          platforms: linux/amd64,linux/arm64
+          driver-opts: |
+            image=moby/buildkit:v0.10.6
+      - name: Docker Hub login
+        uses: docker/login-action@v2.1.0
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_TOKEN }}
+      - name: Build and push
+        uses: docker/build-push-action@v3.2.0
+        with:
+          context: ./docker/dotcms
+          push: true
           tags: ${{ steps.discover-docker-tags.outputs.discovered_tags }}
-          github_user_token: ${{ secrets.CICD_GITHUB_TOKEN }}
-          docker_hub_username: ${{ secrets.DOCKER_USERNAME }}
-          docker_hub_token: ${{ secrets.DOCKER_TOKEN }}
-          dry_run: false
+          platforms: linux/amd64,linux/arm64
+          build-args: |
+            BUILD_FROM=COMMIT
+            BUILD_ID=${{ env.BUILD_ID }}
         if: env.jobRun == 'true'
       - name: Slack Notification
         if: success() && env.jobRun == 'true' 
-        uses: rtCamp/action-slack-notify@master
+        uses: rtCamp/action-slack-notify@v2
         env:
           SLACK_WEBHOOK: ${{ secrets.DEVELOPERS_SLACK_WEBHOOK }}
-          SLACK_USERNAME: dotcms-bot
+          SLACK_USERNAME: dotBot
           SLACK_TITLE: "Attention dotters: Docker image built!"
           SLACK_MSG_AUTHOR: " "
           MSG_MINIMAL: true
